/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.swiftsnail.probe.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MService\",\"namespace\":\"com.swiftsnail.avro.probe.service\",\"types\":[{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.swiftsnail.avro.probe.model\",\"fields\":[{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"sex\",\"type\":\"boolean\"},{\"name\":\"salary\",\"type\":\"double\"},{\"name\":\"childrenCount\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"QueryParameter\",\"namespace\":\"com.swiftsnail.avro.probe.model\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}],\"messages\":{\"ping\":{\"request\":[],\"response\":\"string\"},\"getPersonList\":{\"request\":[{\"name\":\"queryParameter\",\"type\":\"com.swiftsnail.avro.probe.model.QueryParameter\"}],\"response\":{\"type\":\"array\",\"items\":\"com.swiftsnail.avro.probe.model.Person\"}}}}");
  CharSequence ping() throws org.apache.avro.AvroRemoteException;
  java.util.List<com.swiftsnail.avro.probe.model.Person> getPersonList(com.swiftsnail.avro.probe.model.QueryParameter queryParameter) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MService {
    public static final org.apache.avro.Protocol PROTOCOL = MService.PROTOCOL;
    void ping(org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
    void getPersonList(com.swiftsnail.avro.probe.model.QueryParameter queryParameter, org.apache.avro.ipc.Callback<java.util.List<com.swiftsnail.avro.probe.model.Person>> callback) throws java.io.IOException;
  }
}