/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.swiftsnail.probe.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class QueryParameter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"QueryParameter\",\"namespace\":\"com.swiftsnail.avro.probe.model\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int ageStart;
  @Deprecated public int ageEnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public QueryParameter() {}

  /**
   * All-args constructor.
   */
  public QueryParameter(Integer ageStart, Integer ageEnd) {
    this.ageStart = ageStart;
    this.ageEnd = ageEnd;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return ageStart;
    case 1: return ageEnd;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: ageStart = (Integer)value$; break;
    case 1: ageEnd = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ageStart' field.
   */
  public Integer getAgeStart() {
    return ageStart;
  }

  /**
   * Sets the value of the 'ageStart' field.
   * @param value the value to set.
   */
  public void setAgeStart(Integer value) {
    this.ageStart = value;
  }

  /**
   * Gets the value of the 'ageEnd' field.
   */
  public Integer getAgeEnd() {
    return ageEnd;
  }

  /**
   * Sets the value of the 'ageEnd' field.
   * @param value the value to set.
   */
  public void setAgeEnd(Integer value) {
    this.ageEnd = value;
  }

  /** Creates a new QueryParameter RecordBuilder */
  public static QueryParameter.Builder newBuilder() {
    return new QueryParameter.Builder();
  }

  /** Creates a new QueryParameter RecordBuilder by copying an existing Builder */
  public static QueryParameter.Builder newBuilder(QueryParameter.Builder other) {
    return new QueryParameter.Builder(other);
  }

  /** Creates a new QueryParameter RecordBuilder by copying an existing QueryParameter instance */
  public static QueryParameter.Builder newBuilder(QueryParameter other) {
    return new QueryParameter.Builder(other);
  }

  /**
   * RecordBuilder for QueryParameter instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<QueryParameter>
    implements org.apache.avro.data.RecordBuilder<QueryParameter> {

    private int ageStart;
    private int ageEnd;

    /** Creates a new Builder */
    private Builder() {
      super(QueryParameter.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(QueryParameter.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }

    /** Creates a Builder by copying an existing QueryParameter instance */
    private Builder(QueryParameter other) {
            super(QueryParameter.SCHEMA$);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'ageStart' field */
    public Integer getAgeStart() {
      return ageStart;
    }

    /** Sets the value of the 'ageStart' field */
    public QueryParameter.Builder setAgeStart(int value) {
      validate(fields()[0], value);
      this.ageStart = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'ageStart' field has been set */
    public boolean hasAgeStart() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'ageStart' field */
    public QueryParameter.Builder clearAgeStart() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'ageEnd' field */
    public Integer getAgeEnd() {
      return ageEnd;
    }

    /** Sets the value of the 'ageEnd' field */
    public QueryParameter.Builder setAgeEnd(int value) {
      validate(fields()[1], value);
      this.ageEnd = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'ageEnd' field has been set */
    public boolean hasAgeEnd() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'ageEnd' field */
    public QueryParameter.Builder clearAgeEnd() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public QueryParameter build() {
      try {
        QueryParameter record = new QueryParameter();
        record.ageStart = fieldSetFlags()[0] ? this.ageStart : (Integer) defaultValue(fields()[0]);
        record.ageEnd = fieldSetFlags()[1] ? this.ageEnd : (Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
